/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.servicios;

import java.awt.Color;
import java.util.List;
import proyecto.objetos.UsuarioBase;

/**
 *
 * @author milla
 */
public class PanelUsuario extends javax.swing.JPanel {
    private String name;
    private String email;
    private boolean islocked;
    /**
     * Creates new form PanelUsuario
     */
    public PanelUsuario(String name, String email, boolean islocked) {
        initComponents();
        this.name = name;
        this.email = email;
        this.islocked = islocked;
        jLabel1.setText("Nombre: "+name);
        jLabel2.setText("Correo: "+email);
        if(islocked){jLabel3.setText("Estado :Bloqueado");jLabel4.setText("Desbloquear");}else{
            jLabel3.setText("Estado: Normal");
            jLabel4.setText("Bloquear");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Nombre: ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 326, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Correo:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 326, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Estado: ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 326, -1));

        jLabel4.setText("Bloquear");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 100, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 520, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        List<UsuarioBase> usuarios = CreateAcount.leerJSON();
        int indice =0;
        for(UsuarioBase usuario: usuarios){
            if(usuario.getEmail().equals(email)){
                usuario.setLocked(!islocked);
            }
            usuarios.set(indice, usuario);
            indice ++;
        }
        CreateAcount.escribirJSON(usuarios);
        islocked=!islocked;
        if(islocked){
            jLabel3.setText("Estado :Bloqueado");
            jLabel4.setText("Desbloquear");
        }else{
            jLabel3.setText("Estado: Normal");
            jLabel4.setText("Bloquear");
        }
        updateUI();
        Mail.instancia.updateUsuarios();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        jLabel4.setForeground(new Color(251,51,51));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        jLabel4.setForeground(Color.black);
    }//GEN-LAST:event_jLabel4MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
